package com.test.pojo;

import java.io.Serializable;

public class IbEquipmentExport implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IB_EQUIPMENT_EXPORT.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IB_EQUIPMENT_EXPORT.PERIOD
     *
     * @mbggenerated
     */
    private String period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IB_EQUIPMENT_EXPORT.USERID
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IB_EQUIPMENT_EXPORT.GROUPID
     *
     * @mbggenerated
     */
    private Integer groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IB_EQUIPMENT_EXPORT.GROUPNAME
     *
     * @mbggenerated
     */
    private String groupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IB_EQUIPMENT_EXPORT.OVERVIEW
     *
     * @mbggenerated
     */
    private String overview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IB_EQUIPMENT_EXPORT.EQUIPNAME
     *
     * @mbggenerated
     */
    private String equipname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IB_EQUIPMENT_EXPORT.EXPORTER
     *
     * @mbggenerated
     */
    private String exporter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IB_EQUIPMENT_EXPORT.MANUFACTURER
     *
     * @mbggenerated
     */
    private String manufacturer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IB_EQUIPMENT_EXPORT.PRODUCTIONDATE
     *
     * @mbggenerated
     */
    private String productiondate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IB_EQUIPMENT_EXPORT.USESTATE
     *
     * @mbggenerated
     */
    private String usestate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IB_EQUIPMENT_EXPORT.INVESTMENTAMOUNT
     *
     * @mbggenerated
     */
    private String investmentamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IB_EQUIPMENT_EXPORT.CAPACITYSCALE
     *
     * @mbggenerated
     */
    private String capacityscale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IB_EQUIPMENT_EXPORT.APPROVALOPINION
     *
     * @mbggenerated
     */
    private String approvalopinion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IB_EQUIPMENT_EXPORT.ORDERINDEX
     *
     * @mbggenerated
     */
    private Integer orderindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IB_EQUIPMENT_EXPORT.CREATEDATE
     *
     * @mbggenerated
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IB_EQUIPMENT_EXPORT.CREATEUSER
     *
     * @mbggenerated
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IB_EQUIPMENT_EXPORT.COLUMN_1
     *
     * @mbggenerated
     */
    private String column1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IB_EQUIPMENT_EXPORT.COLUMN_2
     *
     * @mbggenerated
     */
    private String column2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IB_EQUIPMENT_EXPORT.COLUMN_3
     *
     * @mbggenerated
     */
    private String column3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IB_EQUIPMENT_EXPORT
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IB_EQUIPMENT_EXPORT.ID
     *
     * @return the value of IB_EQUIPMENT_EXPORT.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IB_EQUIPMENT_EXPORT.ID
     *
     * @param id the value for IB_EQUIPMENT_EXPORT.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IB_EQUIPMENT_EXPORT.PERIOD
     *
     * @return the value of IB_EQUIPMENT_EXPORT.PERIOD
     *
     * @mbggenerated
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IB_EQUIPMENT_EXPORT.PERIOD
     *
     * @param period the value for IB_EQUIPMENT_EXPORT.PERIOD
     *
     * @mbggenerated
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IB_EQUIPMENT_EXPORT.USERID
     *
     * @return the value of IB_EQUIPMENT_EXPORT.USERID
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IB_EQUIPMENT_EXPORT.USERID
     *
     * @param userid the value for IB_EQUIPMENT_EXPORT.USERID
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IB_EQUIPMENT_EXPORT.GROUPID
     *
     * @return the value of IB_EQUIPMENT_EXPORT.GROUPID
     *
     * @mbggenerated
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IB_EQUIPMENT_EXPORT.GROUPID
     *
     * @param groupid the value for IB_EQUIPMENT_EXPORT.GROUPID
     *
     * @mbggenerated
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IB_EQUIPMENT_EXPORT.GROUPNAME
     *
     * @return the value of IB_EQUIPMENT_EXPORT.GROUPNAME
     *
     * @mbggenerated
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IB_EQUIPMENT_EXPORT.GROUPNAME
     *
     * @param groupname the value for IB_EQUIPMENT_EXPORT.GROUPNAME
     *
     * @mbggenerated
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IB_EQUIPMENT_EXPORT.OVERVIEW
     *
     * @return the value of IB_EQUIPMENT_EXPORT.OVERVIEW
     *
     * @mbggenerated
     */
    public String getOverview() {
        return overview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IB_EQUIPMENT_EXPORT.OVERVIEW
     *
     * @param overview the value for IB_EQUIPMENT_EXPORT.OVERVIEW
     *
     * @mbggenerated
     */
    public void setOverview(String overview) {
        this.overview = overview == null ? null : overview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IB_EQUIPMENT_EXPORT.EQUIPNAME
     *
     * @return the value of IB_EQUIPMENT_EXPORT.EQUIPNAME
     *
     * @mbggenerated
     */
    public String getEquipname() {
        return equipname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IB_EQUIPMENT_EXPORT.EQUIPNAME
     *
     * @param equipname the value for IB_EQUIPMENT_EXPORT.EQUIPNAME
     *
     * @mbggenerated
     */
    public void setEquipname(String equipname) {
        this.equipname = equipname == null ? null : equipname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IB_EQUIPMENT_EXPORT.EXPORTER
     *
     * @return the value of IB_EQUIPMENT_EXPORT.EXPORTER
     *
     * @mbggenerated
     */
    public String getExporter() {
        return exporter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IB_EQUIPMENT_EXPORT.EXPORTER
     *
     * @param exporter the value for IB_EQUIPMENT_EXPORT.EXPORTER
     *
     * @mbggenerated
     */
    public void setExporter(String exporter) {
        this.exporter = exporter == null ? null : exporter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IB_EQUIPMENT_EXPORT.MANUFACTURER
     *
     * @return the value of IB_EQUIPMENT_EXPORT.MANUFACTURER
     *
     * @mbggenerated
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IB_EQUIPMENT_EXPORT.MANUFACTURER
     *
     * @param manufacturer the value for IB_EQUIPMENT_EXPORT.MANUFACTURER
     *
     * @mbggenerated
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IB_EQUIPMENT_EXPORT.PRODUCTIONDATE
     *
     * @return the value of IB_EQUIPMENT_EXPORT.PRODUCTIONDATE
     *
     * @mbggenerated
     */
    public String getProductiondate() {
        return productiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IB_EQUIPMENT_EXPORT.PRODUCTIONDATE
     *
     * @param productiondate the value for IB_EQUIPMENT_EXPORT.PRODUCTIONDATE
     *
     * @mbggenerated
     */
    public void setProductiondate(String productiondate) {
        this.productiondate = productiondate == null ? null : productiondate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IB_EQUIPMENT_EXPORT.USESTATE
     *
     * @return the value of IB_EQUIPMENT_EXPORT.USESTATE
     *
     * @mbggenerated
     */
    public String getUsestate() {
        return usestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IB_EQUIPMENT_EXPORT.USESTATE
     *
     * @param usestate the value for IB_EQUIPMENT_EXPORT.USESTATE
     *
     * @mbggenerated
     */
    public void setUsestate(String usestate) {
        this.usestate = usestate == null ? null : usestate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IB_EQUIPMENT_EXPORT.INVESTMENTAMOUNT
     *
     * @return the value of IB_EQUIPMENT_EXPORT.INVESTMENTAMOUNT
     *
     * @mbggenerated
     */
    public String getInvestmentamount() {
        return investmentamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IB_EQUIPMENT_EXPORT.INVESTMENTAMOUNT
     *
     * @param investmentamount the value for IB_EQUIPMENT_EXPORT.INVESTMENTAMOUNT
     *
     * @mbggenerated
     */
    public void setInvestmentamount(String investmentamount) {
        this.investmentamount = investmentamount == null ? null : investmentamount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IB_EQUIPMENT_EXPORT.CAPACITYSCALE
     *
     * @return the value of IB_EQUIPMENT_EXPORT.CAPACITYSCALE
     *
     * @mbggenerated
     */
    public String getCapacityscale() {
        return capacityscale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IB_EQUIPMENT_EXPORT.CAPACITYSCALE
     *
     * @param capacityscale the value for IB_EQUIPMENT_EXPORT.CAPACITYSCALE
     *
     * @mbggenerated
     */
    public void setCapacityscale(String capacityscale) {
        this.capacityscale = capacityscale == null ? null : capacityscale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IB_EQUIPMENT_EXPORT.APPROVALOPINION
     *
     * @return the value of IB_EQUIPMENT_EXPORT.APPROVALOPINION
     *
     * @mbggenerated
     */
    public String getApprovalopinion() {
        return approvalopinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IB_EQUIPMENT_EXPORT.APPROVALOPINION
     *
     * @param approvalopinion the value for IB_EQUIPMENT_EXPORT.APPROVALOPINION
     *
     * @mbggenerated
     */
    public void setApprovalopinion(String approvalopinion) {
        this.approvalopinion = approvalopinion == null ? null : approvalopinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IB_EQUIPMENT_EXPORT.ORDERINDEX
     *
     * @return the value of IB_EQUIPMENT_EXPORT.ORDERINDEX
     *
     * @mbggenerated
     */
    public Integer getOrderindex() {
        return orderindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IB_EQUIPMENT_EXPORT.ORDERINDEX
     *
     * @param orderindex the value for IB_EQUIPMENT_EXPORT.ORDERINDEX
     *
     * @mbggenerated
     */
    public void setOrderindex(Integer orderindex) {
        this.orderindex = orderindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IB_EQUIPMENT_EXPORT.CREATEDATE
     *
     * @return the value of IB_EQUIPMENT_EXPORT.CREATEDATE
     *
     * @mbggenerated
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IB_EQUIPMENT_EXPORT.CREATEDATE
     *
     * @param createdate the value for IB_EQUIPMENT_EXPORT.CREATEDATE
     *
     * @mbggenerated
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IB_EQUIPMENT_EXPORT.CREATEUSER
     *
     * @return the value of IB_EQUIPMENT_EXPORT.CREATEUSER
     *
     * @mbggenerated
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IB_EQUIPMENT_EXPORT.CREATEUSER
     *
     * @param createuser the value for IB_EQUIPMENT_EXPORT.CREATEUSER
     *
     * @mbggenerated
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IB_EQUIPMENT_EXPORT.COLUMN_1
     *
     * @return the value of IB_EQUIPMENT_EXPORT.COLUMN_1
     *
     * @mbggenerated
     */
    public String getColumn1() {
        return column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IB_EQUIPMENT_EXPORT.COLUMN_1
     *
     * @param column1 the value for IB_EQUIPMENT_EXPORT.COLUMN_1
     *
     * @mbggenerated
     */
    public void setColumn1(String column1) {
        this.column1 = column1 == null ? null : column1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IB_EQUIPMENT_EXPORT.COLUMN_2
     *
     * @return the value of IB_EQUIPMENT_EXPORT.COLUMN_2
     *
     * @mbggenerated
     */
    public String getColumn2() {
        return column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IB_EQUIPMENT_EXPORT.COLUMN_2
     *
     * @param column2 the value for IB_EQUIPMENT_EXPORT.COLUMN_2
     *
     * @mbggenerated
     */
    public void setColumn2(String column2) {
        this.column2 = column2 == null ? null : column2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IB_EQUIPMENT_EXPORT.COLUMN_3
     *
     * @return the value of IB_EQUIPMENT_EXPORT.COLUMN_3
     *
     * @mbggenerated
     */
    public String getColumn3() {
        return column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IB_EQUIPMENT_EXPORT.COLUMN_3
     *
     * @param column3 the value for IB_EQUIPMENT_EXPORT.COLUMN_3
     *
     * @mbggenerated
     */
    public void setColumn3(String column3) {
        this.column3 = column3 == null ? null : column3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IB_EQUIPMENT_EXPORT
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IbEquipmentExport other = (IbEquipmentExport) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPeriod() == null ? other.getPeriod() == null : this.getPeriod().equals(other.getPeriod()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getGroupid() == null ? other.getGroupid() == null : this.getGroupid().equals(other.getGroupid()))
            && (this.getGroupname() == null ? other.getGroupname() == null : this.getGroupname().equals(other.getGroupname()))
            && (this.getOverview() == null ? other.getOverview() == null : this.getOverview().equals(other.getOverview()))
            && (this.getEquipname() == null ? other.getEquipname() == null : this.getEquipname().equals(other.getEquipname()))
            && (this.getExporter() == null ? other.getExporter() == null : this.getExporter().equals(other.getExporter()))
            && (this.getManufacturer() == null ? other.getManufacturer() == null : this.getManufacturer().equals(other.getManufacturer()))
            && (this.getProductiondate() == null ? other.getProductiondate() == null : this.getProductiondate().equals(other.getProductiondate()))
            && (this.getUsestate() == null ? other.getUsestate() == null : this.getUsestate().equals(other.getUsestate()))
            && (this.getInvestmentamount() == null ? other.getInvestmentamount() == null : this.getInvestmentamount().equals(other.getInvestmentamount()))
            && (this.getCapacityscale() == null ? other.getCapacityscale() == null : this.getCapacityscale().equals(other.getCapacityscale()))
            && (this.getApprovalopinion() == null ? other.getApprovalopinion() == null : this.getApprovalopinion().equals(other.getApprovalopinion()))
            && (this.getOrderindex() == null ? other.getOrderindex() == null : this.getOrderindex().equals(other.getOrderindex()))
            && (this.getCreatedate() == null ? other.getCreatedate() == null : this.getCreatedate().equals(other.getCreatedate()))
            && (this.getCreateuser() == null ? other.getCreateuser() == null : this.getCreateuser().equals(other.getCreateuser()))
            && (this.getColumn1() == null ? other.getColumn1() == null : this.getColumn1().equals(other.getColumn1()))
            && (this.getColumn2() == null ? other.getColumn2() == null : this.getColumn2().equals(other.getColumn2()))
            && (this.getColumn3() == null ? other.getColumn3() == null : this.getColumn3().equals(other.getColumn3()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IB_EQUIPMENT_EXPORT
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPeriod() == null) ? 0 : getPeriod().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getGroupid() == null) ? 0 : getGroupid().hashCode());
        result = prime * result + ((getGroupname() == null) ? 0 : getGroupname().hashCode());
        result = prime * result + ((getOverview() == null) ? 0 : getOverview().hashCode());
        result = prime * result + ((getEquipname() == null) ? 0 : getEquipname().hashCode());
        result = prime * result + ((getExporter() == null) ? 0 : getExporter().hashCode());
        result = prime * result + ((getManufacturer() == null) ? 0 : getManufacturer().hashCode());
        result = prime * result + ((getProductiondate() == null) ? 0 : getProductiondate().hashCode());
        result = prime * result + ((getUsestate() == null) ? 0 : getUsestate().hashCode());
        result = prime * result + ((getInvestmentamount() == null) ? 0 : getInvestmentamount().hashCode());
        result = prime * result + ((getCapacityscale() == null) ? 0 : getCapacityscale().hashCode());
        result = prime * result + ((getApprovalopinion() == null) ? 0 : getApprovalopinion().hashCode());
        result = prime * result + ((getOrderindex() == null) ? 0 : getOrderindex().hashCode());
        result = prime * result + ((getCreatedate() == null) ? 0 : getCreatedate().hashCode());
        result = prime * result + ((getCreateuser() == null) ? 0 : getCreateuser().hashCode());
        result = prime * result + ((getColumn1() == null) ? 0 : getColumn1().hashCode());
        result = prime * result + ((getColumn2() == null) ? 0 : getColumn2().hashCode());
        result = prime * result + ((getColumn3() == null) ? 0 : getColumn3().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IB_EQUIPMENT_EXPORT
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", period=").append(period);
        sb.append(", userid=").append(userid);
        sb.append(", groupid=").append(groupid);
        sb.append(", groupname=").append(groupname);
        sb.append(", overview=").append(overview);
        sb.append(", equipname=").append(equipname);
        sb.append(", exporter=").append(exporter);
        sb.append(", manufacturer=").append(manufacturer);
        sb.append(", productiondate=").append(productiondate);
        sb.append(", usestate=").append(usestate);
        sb.append(", investmentamount=").append(investmentamount);
        sb.append(", capacityscale=").append(capacityscale);
        sb.append(", approvalopinion=").append(approvalopinion);
        sb.append(", orderindex=").append(orderindex);
        sb.append(", createdate=").append(createdate);
        sb.append(", createuser=").append(createuser);
        sb.append(", column1=").append(column1);
        sb.append(", column2=").append(column2);
        sb.append(", column3=").append(column3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}